### ISSUE TITLE
unknown t sym format

### ISSUE THREAD

**Issue by ajwerner** [knz/go-binsize-viz#12]
I have a go1.22 generated linux binary that has a bunch of symbols that can't be parsed. They have a few different flavors:

* `unknown t sym format: type:.hash.vendor/golang.org/x/net/http2/hpack.pairNameValue`
* `unknown t sym format: stacksviz/ent.withHooks[go.shape.int,go.shape.struct { stacksviz/ent.config; stacksviz/ent.op entgo.io/ent.Op; stacksviz/ent.typ string; stacksviz/ent.id *string; stack
sviz/ent.user_name *string; stacksviz/ent.clearedFields map[string]struct {}; stacksviz/ent.snapshots map[int]struct {}; stacksviz/ent.removedsnapshots map[int]struct {}; stacksviz/ent.clear
edsnapshots bool; stacksviz/ent.done bool; stacksviz/ent.oldValue func(context.Context) (*stacksviz/ent.Binary, error); stacksviz/ent.predicates []stacksviz/ent/predicate.Binary },go.shape.*
stacksviz/ent.BinaryMutation].func1`
* `unknown r sym format: stacksviz/jsondenorm..dict.New[*stacksviz/expb.ProcessSnapshot_CollectedData]`

I've attached the output of `go tool nm -size <file> | c++filt`

[syms.txt](https://github.com/user-attachments/files/15570444/syms.txt)

**Comment by knz** [comment]
fixed in latest commit
