### ISSUE TITLE
unknown B sym format on Windows

### ISSUE THREAD

**Issue by mappu** [knz/go-binsize-viz#2]
Hi! Super cool tool.

I am running this with Go 1.10 `windows/amd64` from golang.org, and Python 3.6 from Cygwin64, on a mixed Go/C (CGO) binary, built with `go build` and nothing more (no `-s -w` etc).

Many such errors during `tab2pydic.py` pass: some representative ones

```
.
unknown D sym format: .CRT$XCA

unknown D sym format: .CRT$XCAA

unknown ? sym format: .file

unknown D sym format: .rsrc

unknown T sym format: .text

unknown B sym format: path/filepath.initdone·

unknown B sym format: reflect.initdone·
.
unknown B sym format: regexp.initdone·

unknown B sym format: regexp/syntax.initdone·

unknown T sym format: type.*
.
unknown B sym format: vendor/golang_org/x/crypto/chacha20poly1305/internal/chacha20.initdone·

unknown B sym format: vendor/golang_org/x/crypto/cryptobyte.initdone·

unknown B sym format: vendor/golang_org/x/net/http2/hpack.initdone·
```

Seems to mostly work aside from this, but the resulting visualisation has a large UNKNOWN section, i guess that's related?

![image](https://user-images.githubusercontent.com/3959202/55363521-cb129400-5539-11e9-8b78-2c2745488ce8.png)

**Comment by knz** [comment]
Thanks for your report! I made a change to include 'initdone·', please try it out.

**Comment by mappu** [comment]
Thanks! Just confirming that did make a big improvement.

Although it didn't seem to affect the tree visualisation in a any material way for my binary.

There are some remaining errors, but very little that points to Go/C code in a specific way.

[tab2pydic_errors.log](https://github.com/knz/go-binsize-viz/files/3035825/tab2pydic_errors.log)

**Comment by knz** [comment]
Could you attach the full output of `go tool nm -size` on your binary. I'd like to understand these formats more.
