### ISSUE TITLE
License

### ISSUE THREAD

**Issue by copy** [knz/go-binsize-viz#5]
I'd like to adapt this project to OCaml, but it's currently unlicensed. Could you add a license?

**Comment by knz** [comment]
NB: the D3 javascript is unlicensed currently:

http://bl.ocks.org/guglielmo/16d880a6615da7f502116220cb551498
http://bl.ocks.org/JacquesJahnichen/42afd0cde7cbf72ecb81

So even if we add a license to the python parts, you'd still be stuck with the visualization.

**Comment by knz** [comment]
Added licensing information to project.
