### ISSUE TITLE
Rewrite in Go or bash?

### ISSUE THREAD

**Issue by ahmetb** [knz/go-binsize-viz#7]
I would super appreciate if this a tool that we can launch with an argument pointing to a Go binary, then it directly launches a web server on localhost:8080 to view the results.

A bash script could do it, too.

The current number of steps to get a result for a binary are simply too many to easily use this tool.

**Comment by phanirithvij** [comment]
There's this PR by @odedpriva https://github.com/knz/go-binsize-viz/pull/6 adding a bash script

**Comment by knz** [comment]
Closing since #6 should solve this problem.
